### ISSUE TITLE
Q: >Also< confused about "smallSoundSensor"

### ISSUE THREAD

**Issue by njackiw** [Alion3064492356/Sensors-for-RaspberryPi#29]
How can I understand the difference between **microphoneSensor** and **smallSoundSensor**?

Is it that **microphoneSensor** is **analogSoundSensor** and **smallSoundSensor** is **convenienceSoundSensor** according to my definition of **convenienceXXX** in #28?

If so, can I rename them 

**old:**
analogHall
magneticHall
linearHall

miniReedSwitch
reedSwitch

analogTempSensor
ds18b20
digitalTempSensor

microphoneSensor
smallSoundSensor

**proposed new:**
analogHall
digitalHall
convenienceHall

reedSwitch (used to be miniReedSwitch)
convenienceReedSwitch

analogTempSensor
digitalTempSensor (used to be ds18b20)
convenienceTempSensor

analogMicrophone
convenienceMicrophone

---
The benefit of these proposed new names is _very big_ for a new user trying to make sense of your technologies, because in comparison to the originals, it is accurate, consistent, and descriptive. In other words, it uses the term "analog" and "digital" correctly rather than incorrectly (accuracy); it uses the same terminology across four different sets of related sensors (consistency); and that terminology actually tells you the **purpose** -- namely user-convenience---of the weird "third type" which is some sort of analog/digital hybrid (descriptiveness). By comparison, the old names are very confusing to an English speaker trying to make sense of your materials. They are frequently unaccurate, and they miss a huge opportunity in which names actually _help_ users come to good understandings of meanings.

However, there is a drawback to adopting the new names, and that is this: you did not make up the old, bad names, or at least not all of them. Many of them are on the internet describing other people's work with the Keyes modules that are the basis of your Kuman modules. So even though "digital Hall effect" descriptively tells me that the output there is going to be a digital True/False signal and "Magnetic Hall Effect" tells me nothing (since ALL hall effects are magnetic), if I GOOGLE "Magnetic Hall Effect Sensor Arduino" I find things based on that specific module. These are easy to find if Kuman keeps using the same bad names for its modules that other manufacturers do, and harder to find if Kuman is the only manufacturer using more descriptive, accurate, and consistent names.

I think there is a strong argument to be made for adopting the new names from the perspective of user understanding, and even perhaps from the perspective of market positioning: Kuman could make a reputation or become a leader in having better materials for new users than people buying their Keyes-knock-off modules off aliBaba or elsewhere. But as the same time, this is not my decision, it should be a business decision you make in consultation with your inhouse business experts.

If we do rename these modules (my vote: yes!), I suggest we provide a brief explanation as well as a list of old names in the READ_ME or another file ... in the same location in which explain to users how many of the different modules fall into groups of related functionality that should best be explored together. This is another place where the new Kuman materials will be making a positive step forward for new users looking for meaningful introductions and conceptual understanding, and a place where we can draw attention to the fact that we are not just doing it _differently_ than, but _better_ than, other manufacturers.

Please think about this and discuss with whomever at Kuman can make these decisions, and let me know your thoughts.

Thank you,
Nick

**Comment by njackiw** [comment]
(If "marketing department" does not want to risk changing the names, we can still try to make the situation clearer for our users by mapping those old-bad-names in individual *.docx experiments to "better" names that are then used in most of the Descriptions. It won't be as bold a step toward clarity as actually renaming the sensors, but it will be better than nothing!)

**Comment by Emily2333** [comment]
Nick,in order to keep correspondence between file and the list,we recommend that it's better to use big sound sensor to replace micro phone sensor.As for rename issue,we checked carefully and finally decide that we keep it at it is without changes cause it's a big project to revise all names at list as well.Please understand how we appreciate that you think so much for us and offered such a considerate suggestion.

**Comment by njackiw** [comment]
Okay, will keep the module names as is (except for "microphone sensor" and a few other preapproved changes [like around the other 3Color LED].), and will also add comments in README.TXT and *.docx files trying to explain how these (not always great) names correspond to analog, digital, or hybrid packages.

Keeping open and assigned to me until I act on this.

**Comment by njackiw** [comment]
Closing this one to clean up open Issue List. We have a bunch of issues that begin about a specific sensor, and wind up in a common conversation about what make good names, what are bad names, and how we handle this for users. We agree on the global strategy, so we no longer need all these original open Issues.
