### ISSUE TITLE
Suggestions for future "ANALOG vs. DIGITAL Experiment Design" (or future experiment revision)

### ISSUE THREAD

**Issue by njackiw** [Alion3064492356/Sensors-for-RaspberryPi#36]
This is just a suggestion for Kuman to consider in the future, as it makes new experiment designs or engages in a more substantial revision of the existing experiments than we are doing now.

Many of these sensors are analog (they report a voltage proportional to some signal), and some are digital (they report a yes/no decision of some sort), and a few are hybrids (they report both a proportional voltage, and a yes/no answer to the question "does that voltage exceed a user-adjustable threshold?" simultaneously).  All good. And, as noted above, even better if and when our experiment names reflect these attributes.  

But the experiments that go with the sensors do not always help "conceptually illuminate" the analog / digital divide. For example, many of our experiments use the sensor to turn on an LED.  Since an LED is either on or off, that's a great experiment design _for a digital sensor_ but not so great a design for an analog one.  In order to use that design with analog sensors, our Sample Code has to compare the proportional voltage to a fixed threshold defined by the code, and then convert it from a real number into a boolean (digital) decision, "on" or "off."  In essence, the source code creates a hybridExperiment out of an analogSensor.

By contrast, some of our other experiments print number information to the command line. This is very flexible, and we can report on things like ANALOG quantities, which are variable and continuous ("The temperature is 43° ... 44° .... 45° .... 46°") and not just digital ones, which are discrete and often simply binary ("The light sensor is BLOCKED ... the light sensor is CLEAR ... BLOCKED ... CLEAR ...").

I encourage Kuman when designing future experiments, or majorly revising its existing ones, to try to have the experiment design reflect the ANALOG vs. DIGITAL nature of the sensor being demonstrated. So for ANALOG sensors, choose outputs like the command-line, or other continuous and variable outputs (pitch in the passiveBuzzer might be a nice one!),   rather than digital outputs like whether the LED is illuminated.  Similarly, for DIGITAL sensors, design experiments that demonstrate them through more "digital" or discrete outputs (like the LED, the relay, the active buzzer, or other "on/off" devices).  Having the experiment "output" mirror the experiment "input" like this would help simplify and clarify both the experiment code, and the nature of the sensor being demonstrated by the experiment, for both new users and perhaps even for seasoned users checking back for some "borrowable" sample code or quick insight into a familiar sensor.

No need for action on any of this in K47 (unless you want me to start rewriting experiments from scratch :-)!)

**Comment by Alion3064492356** [comment]
Thanks for your suggestions! We will seriously consider your suggestions and put it into practice in future projects.
Thanks again!
