### ISSUE TITLE
Q: DS18B20 Digital Temperature Sensor/Why "Tip?"

### ISSUE THREAD

**Issue by njackiw** [Alion3064492356/Sensors-for-RaspberryPi#37]

**Comment by njackiw** [comment]
DS18B20's pin diagram says
>DS18B20 pin position:
>	"S" =====> 7
>	"+" =====> +5V
>	"-" =====> GND
	
>Tips:Ds18b20's data pin must be connect GPIO7

Question: why the tip? It already says "S" ===> "pin 7" above --- Is there a requirement here that is more severe than any other pin mapping? If so, what is it? In other words, is there something technical and specific here that we should explain to the user?  Right now the "tip" says the same thing as the table---map the sensor output to pin 7!---so leaves me confused why we are saying it twice...

**Comment by njackiw** [comment]
Ah, makes sense. So, does the following sound correct?

> NOTE:  The Raspberry Pi's libraries  _only_ work with DS18B20 "S" pin connected to GPI07. If you design your own experiments for DS18B20 or write your own DS18B20 source code, do not change  pin mapping.

If so, I'll put it both DOCX itself rather than just in the CorrespondingPinTable.txt.

Let me know, thanks.

**Comment by Emily2333** [comment]
Hi Nick,after checking with Leng,you can use the "note" content to replace original "Tip" content if you think that part was double expressed.

**Comment by njackiw** [comment]
done, thanks.
