### ISSUE TITLE
DHT11 tempHumiditySensor: code improvement request

### ISSUE THREAD

**Issue by njackiw** [Alion3064492356/Sensors-for-RaspberryPi#39]
dht11.c here begins: 

```
printf("Use GPIO1 to read data!\n");  
  
  if (-1 == wiringPiSetup()) 
  {  
    printf("Setup wiringPi failed!");  
    return -1;  
  }  
   
  pinMode(pinNumber, OUTPUT); // set mode to output  
  digitalWrite(pinNumber, 1); // output a high level   
  
  printf("Enter OS-------\n");
```
What is the meaning of the printf statements about GPIO1 (at the top) or about Enter OS (at the bottom)? Pin & Wiring Diagrams & "int pinNumber = 7" all suggest we are using pin 7, not GPIO1.

I think these printf() statements might be leftovers from some other program.  Can we just delete both these printf statements from the C code (and the docx/Sample Code/C Code listing)?

**Comment by Alion3064492356** [comment]
Both these printf() statements are debug message, we could delete them.
