### ISSUE TITLE
metalTouchSensor: code request

### ISSUE THREAD

**Issue by njackiw** [Alion3064492356/Sensors-for-RaspberryPi#53]
Current code (C and Python) only reports the analog output when it exceeds threshold (i.e. when the digital switch signals):

```
while(1){
		if((digitalVal = digitalRead(Touch_DO_Pin)))
		{
			printf("Do is %d.\n", digitalVal);
			printf("Touch detected...");
			printf("Current analog value is %d.\n", get_ADC_Result());
			delay(200);
		}
		else
		{
			;
		}

	}
```

Could we change it (both C and Python) so that analog output is reported periodically regardless of whether touch is happening or not, and digital output is reported separately? More like

```
while (1)
{
      printf("Current analog value is %d.\n", get_ADC_Result());
      if((digitalVal = digitalRead(Touch_DO_Pin)))
		printf("Do is %d.\n", digitalVal);
      delay(200);
}
```

Then users can see the analog difference between below **and** above threshold conditions, and  if the threshold is set poorly, can see at least how the analog sensor behaving, and adjust the threshold trimPot to a better position.

**Comment by Alion3064492356** [comment]
Okay, I have done this work.

**Comment by njackiw** [comment]
closing...
