### ISSUE TITLE
Kuman Packaging Question: What documentation files to ship to users?

### ISSUE THREAD

**Issue by njackiw** [Alion3064492356/Sensors-for-RaspberryPi#55]
Since my instructions have been to help make this simpler and clearer for users, now's the time for me to say this: the file and folder structure in your packaging is somewhat confusing and could be a lot simpler!

The original K47 kits comes with many sensor folders (good), each of which obeys the same structure (good), and contains the following layout for imaginary experiment _xxx_:

- _xxx_ (folder)
- - Code (folder)
- - - C (folder)
_xxx_.c
- - - Python (folder)
_xxx_.py
maybe some other optional Python files, e.g. ADC.py
- - Connection method (folder)
Pin position corresponding table.txt
_xxx_.cdr
_xxx_.jpg
- - Description (folder)
_xxx_.docx

This is much less good, for several reasons:

1. It's complicated. Lots of subfolders that only have one file in them.
2. It's redundant. The same information, e.g. the wiring diagram, shows up in three different files (*.cdr, *.jpg, and *.docx). The pintable shows up in two different files. Each Code program shows up in two different files. New users spend a lot of time looking around and seeing what looks like the same information in different places. Is it the same? Or is it subtly different? Also, redundancy gives us more opportunity for making mistakes keeping different copies of "the same information" synchronized and current.
3. Some of it is in hard-to-read formats. I have a half-dozen different computers none of which knows what to do with a *.cdr file. As I understand it, lots of Mac owners cannot open a *.docx file, and since *.docx is a proprietary format, even the "public domain docx viewers" don't do a great job with all of Microsoft Word's possible formatting.

I encourage Kuman to move to a simpler situation, both to simplify their customers' understandings and also to improve their own workflow producing and maintaining these documentation files. Ingredients of a good solution would be:
a. Less complicated per-sensor subfolder structure
b. User files only in universally-accessible formats: plain text (*.txt, *.c, *.py), HTML, and PDF

That is a long-term goal, because it requires Kuman to separate its _production_ files (*.docx and perhaps *.cdr or Fritzing originals) from its _distribution_ files. If you were a software development house, you would have a GitHub repository that contained both hierarchies (ProductionMasters/ vs. UserDocs/), and a script that created UserDocs from the ProductionMasters after every commit to ProductionMasters, and you would open at least the UserDocs/ repo to the whole world) :-).

However, as a *short-term* goal, e.g. in K47, you could still make many improvements here. Here are my suggestions, in order of importance:

1. Get rid of the "Connection method" folder entirely. Everything in it is already in, and redundant with, the *.docx file.  (Don't get rid of "Code", which is also redunant, because people actually need Code files as standalone files to feed to their C compiler or Python interpreter.)

2. Either replace the *.docx files with *.pdf files, or shadow both in the same directory. This will be a hassle to produce without an automated tool to do it for us, but will increase accessibility of your files, I think a lot. If we do this, we should add "edit dates" or "revision numbers" to the .DOCX files (e.g. in a page footer), so we can tell whether a found PDF file is actually identical to a found DOCX file.

3. Simplify internal folder structure to this:

 - _xxx_ (folder)
_xxx_.docx
xxx_.pdf (identical)
- - Code (folder)
_xxx_.c
_xxx_.py
optional other Python files

You can think of these last three things as **Nick's proposals for K47 package redesign.** Let me know if you want to act on any of them. Otherwise, please consider them suggestions for Kuman to "think about" as you continue to develop and revise your products for global markets!

**Comment by Alion3064492356** [comment]
What I can confirm now is that we will eventually provide customers with .pdf files instead of .doc files after we confirm there are no big problem in these experiments.

**Comment by Alion3064492356** [comment]
Thanks, Nick!
We could delete pin position table.txt and  .cdr , and convert .doc into .pdf when we finally complete this task.But now we need to keep them so as to revise these experiments.
I agree to move .doc into top level folder and delete folder "decription".

**Comment by njackiw** [comment]
My Pull Request just now (#58) takes care of the "move .doc into top level folder and delete folder "decription" part of this.

We should still think about getting rid of Connection folder entirely from the end-user product. Nothing in it is not already in DOCX, so everything there is redundant. I think we could move it into another high-level folder in GIT, "DEVELOPMENT MATERIALS", so we can still access it to modify Fritzing diagrams etc.,  but don't ship it to users.  (Similarly we could keep .DOCX there and .PDFS for users.) Let's do this later, though ... doesn't have to happen now.
