### ISSUE TITLE
Q: AnalogHall/Voltage Difference?

### ISSUE THREAD

**Issue by njackiw** [Alion3064492356/Sensors-for-RaspberryPi#9]
The original analogHall Description says

> A voltage difference is generated when the Hall element and the magnet meet in the forward direction, and there is no voltage difference when the Hall element and the magnet meet in the forward direction.

This is contradictory. Either there IS a voltage difference in the forward direction or there IS NO voltage difference in the forward direction, but it can't be both.  I think maybe one time you mean “backward” and the other time “forward” but can’t quickly decide which one is which! What is correct here?

Please answer and assign back to Nick for correction in the Word file.

**Comment by Alion3064492356** [comment]
A voltage difference is generated when the Hall element and the magnet meet in the forward direction, and there is no voltage difference when the Hall element and the magnet meet in the inverse direction.

**Comment by njackiw** [comment]
Excellent; I will fix in a coming commit. Thanks.
